# Generated by Django 4.2 on 2023-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueName', models.CharField(max_length=20)),
                ('creatorID', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=100)),
                ('array', models.TextField(default='[]')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
