# Generated by Django 4.2 on 2023-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0002_queue_alter_user_data_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='speedData',
            field=models.CharField(default='3000#2023-04-25 23:13:33', max_length=50),
        ),
    ]
