# Generated by Django 4.2 on 2023-04-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0003_queue_speeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joinedQueue',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='myQueue',
            field=models.TextField(default='[]'),
        ),
    ]
