# Generated by Django 4.2 on 2023-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0004_user_joinedqueue_user_myqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='speedData',
            field=models.CharField(default='300#2023-04-25 23:13:33', max_length=50),
        ),
    ]
